import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import Link from "next/link"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				{children}
				<Toaster richColors position="top-right" />
			</body>
		</html>
	)
}

const Header = () => {
	return (
		<header className="w-full h-16 flex items-center justify-center gap-24 bg-slate-600/20">
			<h1>CRUD con SWR</h1>
			<Link href="/">Todos</Link>
			<Link href="/mongo">Mongo</Link>
		</header>
	)
}
